Connectivity:
  name: Savienojamība
Development:
  name: Izstrāde
Games:
  name: Spēles
Graphics:
  name: Grafika
Internet:
  name: Internets
Money:
  name: Nauda
Multimedia:
  name: Multivide
Navigation:
  name: Kartes un pārvietošanās norādes
Phone & SMS:
  name: Tālrunis un īsziņas
Reading:
  name: Lasīšana
Science & Education:
  name: Zinātne un izglītība
Security:
  name: Drošība
Sports & Health:
  name: Sports un veselība
System:
  name: Sistēma
Theming:
  name: Izskats
Time:
  name: Laiks
Writing:
  name: Rakstīšana
Email:
  name: E-pasts
DNS & Hosts:
  name: DNS un mitinātāji
App Store & Updater:
  name: Lietotņu veikals un atjauninātājs
Browser:
  name: Pārlūks
File Transfer:
  name: Datņu pārsūtīšana
File Encryption & Vault:
  name: Datņu šifrēšana un glabātava
Local Media Player:
  name: Vietējo informācijas nesēju atskaņotājs
Messaging:
  name: Ziņapmaiņa
Weather:
  name: Laikapstākļi
Podcast:
  name: Raidieraksts
News:
  name: Ziņas
Online Media Player:
  name: Tiešsaistes informācijas nesēju atskaņotājs
Social Network:
  name: Sabiedriskais tīkls
VPN & Proxy:
  name: VPN un starpniekserveris
Keyboard & IME:
  name: Tastatūra un ievades veidu redaktors
Cloud Storage & File Sync:
  name: Mākoņkrātuve un datņu sinhronizēšana
Password & 2FA:
  name: Paroles un divpakāpju autentificēšana
Calendar & Agenda:
  name: Kalendārs un dienaskārtība
Voice & Video Chat:
  name: Balss un video tērzēšana
Wallet:
  name: Maks
Bookmark:
  name: Grāmatzīme
Calculator:
  name: Skaitļotājs
Draw:
  name: Zīmēšana
Ebook Reader:
  name: E-grāmatu lasītājs
Finance Manager:
  name: Naudas līdzekļu pārvaldnieks
Gallery:
  name: Galerija
Icon Pack:
  name: Ikonu paka
Launcher:
  name: Palaidējs
Note:
  name: Piezīme
Pass Wallet:
  name: Caurlaižu maks
Recipe Manager:
  name: Recepšu pārvaldnieks
Text Editor:
  name: Teksta redaktors
Translation & Dictionary:
  name: Tulkošana un vārdnīca
Unit Convertor:
  name: Vienību pārveidotājs
Wallpaper:
  name: Ekrāntapete
Workout:
  name: Trenēšanās
Public Transport Map & Timetable:
  name: Publiskā transporta karte un kustības saraksts
Task:
  name: Uzdevums
Shopping List:
  name: Iepirkumu saraksts
