Ads:
  description: Esta aplicación tiene publicidad
  name: Anuncios
DisabledAlgorithm:
  description: Esta aplicación tiene una firma de seguridad muy débil
  name: Firmado con un algoritmo inseguro
KnownVuln:
  description: Esta aplicación contiene una vulnerabilidad de seguridad conocida
  name: Vulnerabilidad conocida
NSFW:
  description: Esta aplicación permite ver contenido que puede no ser apto para todos los públicos
  name: Contenido para adultos
NoSourceSince:
  name: El código fuente ya no está disponible, por lo que no tendrá versiones nuevas.
NonFreeAdd:
  description: Esta aplicación promueve complementos no libres
  name: Complementos no libres
NonFreeAssets:
  description: Esta aplicación contiene datos, imágenes o textos que no son libres
  name: Elementos no libres
NonFreeDep:
  description: Esta aplicación depende de otras que no son libres
  name: Dependencias no libres
NonFreeNet:
  description: Esta aplicación promueve o se conecta a servidores remotos que no son libres
  name: Servicios de red no libres
Tracking:
  description: Esta aplicación sigue lo que haces e informa de tu actividad
  name: Rastreo y seguimiento
TetheredNet:
  description: Esta aplicación depende de que un único servidor remoto de un tercero esté activo para funcionar
  name: Unido a un único servicio de red
