archive:
  description: Arkiv för F-Droids officiella förråd för fri mjukvara. Appar här är gamla och kan innehålla kända sårbarheter och säkerhetsproblem!
  name: F-Droid arkiv
repo:
  description: Det officiella F-Droid Free Software-repositoriet. Allt i detta repositorie är alltid byggt från källkoden.
  name: F-Droid
