Categories:
  - System
License: GPL-3.0-only
AuthorName: RBN-Apps
SourceCode: https://github.com/RBN-Apps/Quick-Tile-Settings
IssueTracker: https://github.com/RBN-Apps/Quick-Tile-Settings/issues

AutoName: QuickTile Settings

RepoType: git
Repo: https://github.com/RBN-Apps/Quick-Tile-Settings.git
Binaries: https://github.com/RBN-Apps/Quick-Tile-Settings/releases/download/v%v/quick-tile-settings-%v.apk

Builds:
  - versionName: 1.1.1
    versionCode: 5
    commit: d6561ed10be3b8ada0fe58f804db906897301d23
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

  - versionName: 1.1.2
    versionCode: 6
    commit: 0c1873482267b8a45fe3b3d12130efe574dcf54d
    subdir: app
    gradle:
      - yes
    srclibs:
      - reproducible-apk-tools@v0.3.0
    postbuild:
      - mv $$OUT$$ unaligned.apk
      - $$reproducible-apk-tools$$/zipalign.py --page-size 16 --pad-like-apksigner
        --replace unaligned.apk $$OUT$$

AllowedAPKSigningKeys: 9766c553571586193a9e0fa7145794aff73201609012ea8cdaff08d85941987b

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 1.1.2
CurrentVersionCode: 6
