AntiFeatures:
  NonFreeNet:
    en-US: The app uses an API at crpt.ru
    ru-RU: Использование API сайта crpt.ru
Categories:
  - Sports & Health
License: GPL-3.0-only
AuthorName: pewaru-333
SourceCode: https://github.com/pewaru-333/HomeMedkit-App
IssueTracker: https://github.com/pewaru-333/HomeMedkit-App/issues
Changelog: https://github.com/pewaru-333/HomeMedkit-App/releases

AutoName: Medkit

RepoType: git
Repo: https://github.com/pewaru-333/HomeMedkit-App.git
Binaries: https://github.com/pewaru-333/HomeMedkit-App/releases/download/%v/HomeMedkit.apk

Builds:
  - versionName: 1.5.6
    versionCode: 41
    commit: f9952f205ec30cc0429e964033ae16fc7f7c027f
    subdir: app
    gradle:
      - yes

  - versionName: 1.5.8
    versionCode: 43
    commit: 6771950d28673b5127c4988c22d39eee65092761
    subdir: app
    gradle:
      - yes

  - versionName: 1.6.0
    versionCode: 44
    commit: 083cb1e0e78d2e8dee281447d33914eeb81cf049
    subdir: app
    gradle:
      - yes

  - versionName: 1.6.2
    versionCode: 46
    commit: 79499fa0d6a2047520b0e5fb4a8d7b439bd91724
    subdir: app
    gradle:
      - yes

  - versionName: 1.6.3
    versionCode: 47
    commit: 0055c92bc4fefb043a8396a2aed8d23f44081520
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.0-beta
    versionCode: 48
    commit: a78f09e7ad9dc8592ed29a10d02c42cffb407f83
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.1
    versionCode: 49
    commit: 1b2bf982d005c7b24b812736e64db57868bd8b27
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.2
    versionCode: 50
    commit: d195d46bee7700075a7481db6e62e4f62a6b2c30
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.3
    versionCode: 51
    commit: 878ef51f3b4bfafa6f88de764819e30c008aced3
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.7
    versionCode: 52
    commit: e52138113d817905836cbcf754ab924670f7502f
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.8
    versionCode: 53
    commit: 12d233e3426590e979e1c75524da8cb11bbdd5b1
    subdir: app
    gradle:
      - yes

  - versionName: 1.7.9
    versionCode: 54
    commit: 5ba75a7eeb1652c4dd813a2038345c818d8e6adf
    subdir: app
    gradle:
      - yes

  - versionName: 1.8.0
    versionCode: 55
    commit: 0163c558dd9667bf6d62bc5d038bda0c0b3208a0
    subdir: app
    gradle:
      - yes

  - versionName: 1.8.1
    versionCode: 56
    commit: 336691c88010b1577ec403c6501cb308d86031a4
    subdir: app
    gradle:
      - yes

AllowedAPKSigningKeys: d5f652d2ec10bfb7915a2981eb6426624fc5229293bf620a6124d6839af179ea

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckIgnore: (alpha|beta|rc|RC|dev)
CurrentVersion: 1.8.1
CurrentVersionCode: 56
