Connectivity:
  name: Forbindelse
Development:
  name: Udvikling
Games:
  name: Spil
Graphics:
  name: Grafik
Internet:
  name: Internet
Money:
  name: Penge
Multimedia:
  name: Multimedier
Navigation:
  name: Navigation
Phone & SMS:
  name: Telefon & SMS
Reading:
  name: Læsning
Science & Education:
  name: Videnskab & Uddannelse
Security:
  name: Sikkerhed
Sports & Health:
  name: Sport & Sundhed
System:
  name: System
Theming:
  name: Temaer
Time:
  name: Tid
Writing:
  name: Skrivning
