Connectivity:
  name: Bağlanabilirlik
Development:
  name: Geliştirme
Games:
  name: Oyunlar
Graphics:
  name: Çizim
Internet:
  name: İnternet
Money:
  name: Finans
Multimedia:
  name: Çoklu ortam
Navigation:
  name: Navigasyon
Phone & SMS:
  name: Telefon ve SMS
Reading:
  name: Okuma
Science & Education:
  name: Bilim ve eğitim
Security:
  name: Güvenlik
Sports & Health:
  name: Spor ve Sağlık
System:
  name: Sistem
Theming:
  name: Tema
Time:
  name: Zaman
Writing:
  name: Yazım
Bookmark:
  name: Yer imi
Browser:
  name: Tarayıcı
Calculator:
  name: Hesap Makinesi
Calendar & Agenda:
  name: Takvim ve Ajanda
Cloud Storage & File Sync:
  name: Bulut Depolama ve Dosya Eşzamanlama
Draw:
  name: Çizim
Ebook Reader:
  name: E-Kitap Okuyucu
Email:
  name: E-posta
File Transfer:
  name: Dosya Aktarımı
Gallery:
  name: Galeri
Icon Pack:
  name: Simge Paketi
Keyboard & IME:
  name: Klavye ve Giriş Yöntemi Düzenleyici
Launcher:
  name: Başlatıcı
News:
  name: Haberler
Note:
  name: Not
Online Media Player:
  name: Çevrimiçi Ortam Oynatıcı
Social Network:
  name: Sosyal Ağ
Text Editor:
  name: Metin Düzenleyici
Translation & Dictionary:
  name: Çeviri ve Sözlük
Unit Convertor:
  name: Birim Dönüştürücü
Voice & Video Chat:
  name: Sesli ve Görüntülü Görüşme
Wallet:
  name: Cüzdan
Wallpaper:
  name: Duvar kağıdı
Weather:
  name: Hava Durumu
App Store & Updater:
  name: Uygulama Deposu ve Güncelleyici
