Ads:
  description: بۇ ئەپتە ئېلان بار
  name: ئېلان
NonFreeAdd:
  description: بۇ ئەپ ھەقسىز بولمىغان قىستۇرمىلارنى تەۋسىيە قىلىدۇ
  name: ئەركىن بولمىغان قوشۇلما
NonFreeDep:
  description: بۇ ئەپ ھەقسىز بولمىغان باشقا ئەپلەرگە بېقىنىدۇ
  name: ئەركىن بولمىغان تايانچ
NonFreeNet:
  description: بۇ ئەپ ھەقسىز بولمىغان تور مۇلازىمەتلىرىنى تەۋسىيە قىلىدۇ
  name: ئەركىن بولمىغان تور مۇلازىمىتى
Tracking:
  description: بۇ ئەپ پائالىيەتلىرىڭىزنى ئىزلاپ، دوكلات قىلىدۇ
  name: ئىزلاش
DisabledAlgorithm:
  description: بۇ ئەپنىڭ ئاجىز ئىمزاسى بار
  name: بىخەتەر بولمىغان ھېسابلاش ئۇسۇلى ئىشلىتىپ ئىمزا قويۇلغان
TetheredNet:
  name: تور مۇلازىمىتىگە باغلانغان
  description: بۇ ئەپ پۈتۈنلەي مەلۇم بىر تور مۇلازىمىتىگە تايىنىدۇ
KnownVuln:
  description: بۇ ئەپتە بىلىنگەن بىخەتەرلىك يوچۇقى بار
  name: بىلىنگەن بىخەتەرلىك يوچۇقى
NSFW:
  description: بۇ ئەپتە خالىغان جايدا ئاشكارا كۆرسەتكىلى ياكى كۆرگىلى بولمايدىغان مەزمۇن بار
  name: NSFW
NoSourceSince:
  name: ئەسلى كودىنى ئەمدى ئىشلەتكىلى بولمايدۇ، يېڭىلىغىلى بولمايدۇ.
NonFreeAssets:
  description: بۇ ئەپتە ئەركىن بولمىغان مەنبە بار
  name: ئەركىن بولمىغان مەنبە
