archive:
  name: F-Droid ئارخىپ
  description: رەسمىي F-Droid ئەركىن يۇمشاق دېتال خەزىنە ئارخىپى. بۇ جايدىكى ئەپلەرنىڭ تارىخى ئۇزۇن، بىلىنگەن يوچۇق ۋە بىخەتەرلىك مەسىلىسى بولۇشى مۇمكىن!
repo:
  name: F-Droid
  description: رەسمىي F-Droid ئەركىن يۇمشاق دېتال خەزىنىسى. بۇ خەزىنەدىكى ھەممىسى ھەمىشە ئەسلى كودتىن قۇرۇلىدۇ.
