archive:
  name: எஃப்-டிராய்டு காப்பகம்
  description: அதிகாரப்பூர்வ எஃப்-டிராய்டு இலவச மென்பொருள் களஞ்சியத்தின் காப்பகம். இங்குள்ள பயன்பாடுகள் பழையவை மற்றும் அறியப்பட்ட பாதிப்புகள் மற்றும் பாதுகாப்பு சிக்கல்களைக் கொண்டிருக்கலாம்!
repo:
  name: எஃப்-டிராய்டு
  description: அதிகாரப்பூர்வ எஃப்-டிராய்டு இலவச மென்பொருள் களஞ்சியம். இந்த களஞ்சியத்தில் உள்ள அனைத்தும் எப்போதும் மூலக் குறியீட்டிலிருந்து கட்டமைக்கப்படுகின்றன.
