Ads:
  description: Esta aplicação contém publicidade
  name: Anúncios
DisabledAlgorithm:
  description: Esta aplicação tem uma assinatura de segurança fraca
  name: Assinado usando um algoritmo inseguro
KnownVuln:
  description: Esta aplicação contém uma falha de segurança conhecida
  name: Vulnerabilidade conhecida
NSFW:
  description: Esta aplicação contém conteúdos que não devem ser divulgados ou visíveis em todo o lado
  name: NSFW
NoSourceSince:
  name: O código-fonte já não está disponível, não é possível ter atualizações.
NonFreeAdd:
  description: Esta aplicação promove complementos não-livres
  name: Complementos não-livres
NonFreeAssets:
  description: Esta aplicação contém conteúdo não-livre
  name: Conteúdos não livres
NonFreeDep:
  description: Esta aplicação depende de outras aplicações não-livres
  name: Dependências não-livres
NonFreeNet:
  description: Esta aplicação promove ou depende inteiramente de um serviço de rede não-livre
  name: Serviços de rede não-livres
Tracking:
  description: Esta aplicação monitoriza e reporta a sua atividade
  name: Rastreamento
TetheredNet:
  description: Esta aplicação depende inteiramente de uma determinada instância de um serviço de rede
  name: Serviços de Rede Tethered
