Connectivity:
  name: Łączność
Development:
  name: Rozwój
Games:
  name: Gry
Graphics:
  name: Grafika
Internet:
  name: Internet
Money:
  name: Finanse
Multimedia:
  name: Multimedia
Navigation:
  name: Nawigacja
Phone & SMS:
  name: Telefon i SMS
Reading:
  name: Czytanie
Science & Education:
  name: Nauka i edukacja
Security:
  name: Bezpieczeństwo
Sports & Health:
  name: Sport i zdrowie
System:
  name: System
Theming:
  name: Motywy
Time:
  name: Czas
Writing:
  name: Pisanie
Email:
  name: E-mail
VPN & Proxy:
  name: VPN i proxy
DNS & Hosts:
  name: DNS i hosty
File Encryption & Vault:
  name: Szyfrowanie plików i sejf
Password & 2FA:
  name: Hasło i uwierzytelnianie dwuskładnikowe (2FA)
Messaging:
  name: Komunikacja
File Transfer:
  name: Przesyłanie plików
Social Network:
  name: Sieć społecznościowa
App Store & Updater:
  name: Sklep z aplikacjami i aktualizator
Browser:
  name: Przeglądarka
Local Media Player:
  name: Lokalny odtwarzacz multimediów
News:
  name: Wiadomości
Online Media Player:
  name: Odtwarzacz multimediów online
Keyboard & IME:
  name: Klawiatura i IME
Weather:
  name: Pogoda
Podcast:
  name: Podcast
Cloud Storage & File Sync:
  name: Przechowywanie w chmurze i synchronizacja plików
Wallet:
  name: Portfel
Voice & Video Chat:
  name: Czat głosowy i wideo
Calendar & Agenda:
  name: Kalendarz i harmonogram
Bookmark:
  name: Zakładka
Calculator:
  name: Kalkulator
Draw:
  name: Szkicownik
Ebook Reader:
  name: Czytnik e-booków
Finance Manager:
  name: Zarządzanie finansami
Gallery:
  name: Galeria
Icon Pack:
  name: Pakiet ikon
Launcher:
  name: Launcher
Note:
  name: Notatka
Pass Wallet:
  name: Portfel haseł
Recipe Manager:
  name: Menedżer przepisów
Text Editor:
  name: Edytor tekstu
Translation & Dictionary:
  name: Tłumaczenie i słownik
Unit Convertor:
  name: Konwerter jednostek
Wallpaper:
  name: Tapeta
Workout:
  name: Trening
Public Transport Map & Timetable:
  name: Mapa transportu publicznego i rozkład jazdy
Task:
  name: Zadanie
Shopping List:
  name: Lista zakupów
