Connectivity:
  name: Connectivité
Development:
  name: Développement
Games:
  name: Jeux
Graphics:
  name: Graphisme
Internet:
  name: Internet
Money:
  name: Finances
Multimedia:
  name: Multimédia
Navigation:
  name: Navigation
Phone & SMS:
  name: Téléphone et SMS
Reading:
  name: Lecture
Science & Education:
  name: Science et éducation
Security:
  name: Sécurité
Sports & Health:
  name: Sport et santé
System:
  name: Système
Theming:
  name: Personnalisation
Time:
  name: Temps
Writing:
  name: Écriture
Calendar & Agenda:
  name: Calendrier & Agenda
Cloud Storage & File Sync:
  name: Stockage dans le cloud & Synchronisation de fichiers
Messaging:
  name: Messagerie
News:
  name: Nouvelles
Social Network:
  name: Réseau social
Wallet:
  name: Portefeuille
Voice & Video Chat:
  name: Chat vocal & vidéo
Online Media Player:
  name: Lecteur Multimédia en Ligne
Password & 2FA:
  name: Mot de passe & 2FA
Podcast:
  name: Podcast
Weather:
  name: Météo
VPN & Proxy:
  name: VPN & Proxy
DNS & Hosts:
  name: DNS & Hôtes
Email:
  name: E-mail
App Store & Updater:
  name: App Store et Programme de mise à jour
Browser:
  name: Navigateur
File Encryption & Vault:
  name: Cryptage de fichiers & Coffre-fort
File Transfer:
  name: Transfert de fichiers
Keyboard & IME:
  name: Clavier & IME
Local Media Player:
  name: Lecteur Multimédia Local
Bookmark:
  name: Signet
Calculator:
  name: Calculatrice
Draw:
  name: Dessiner
Ebook Reader:
  name: Livre électronique
Finance Manager:
  name: Directeur financier
Gallery:
  name: Galerie
Icon Pack:
  name: Pack d'icônes
Launcher:
  name: Lanceur
Note:
  name: Note
Pass Wallet:
  name: Portefeuille Pass
Recipe Manager:
  name: Gestionnaire de recettes
Text Editor:
  name: Éditeur de texte
Translation & Dictionary:
  name: Traduction et Dictionnaire
Unit Convertor:
  name: Convertisseur d'unités
Wallpaper:
  name: Fonds d'écran
Workout:
  name: Entraînement
Public Transport Map & Timetable:
  name: Plan et Horaires des transports en commun
Shopping List:
  name: Liste de courses
Task:
  name: Tâche
