Development:
  name: Diorren
Connectivity:
  name: Kevreadusted
Games:
  name: C'hoarioù
Reading:
  name: Lenn
Graphics:
  name: Graferezh
Money:
  name: Arc'hant
Multimedia:
  name: Liesvedia
Navigation:
  name: Merdeiñ
Phone & SMS:
  name: Pellgomz hag SMS
Security:
  name: Diogelroez
Sports & Health:
  name: Sportoù ha yec'hed
System:
  name: Reizhiad
Theming:
  name: Neuz
Time:
  name: Eur
Writing:
  name: Skrivañ
Internet:
  name: Internet
Science & Education:
  name: Skiantoù ha deskadurezh
