Ads:
  description: Был ҡушымтала реклама бар
  name: Реклама
DisabledAlgorithm:
  description: Был ҡушымтаның хәүефһеҙлек сигнатураһы көсһөҙ
  name: Ҡултамға хәүефле алгоритм менән ҡуйылған
NSFW:
  description: Был ҡушымтала дөйөм ҡарау өсөн тәғәйенләнмәгән эстәлек бар
  name: 18+
NoSourceSince:
  name: Сығанаҡ код булмағанға, яңыртыу мөмкин түгел.
NonFreeAssets:
  description: Был ҡушымтала түләүле ресурстар бар
  name: Түләүле ресурстар
NonFreeAdd:
  name: Түләүле өҫтәмәләр
  description: Был ҡушымта түләүле өҫтәмәләр тәҡдим итә
KnownVuln:
  name: Билдәле проблема
  description: Был ҡушымтала билдәле хәүефһеҙлек проблемаһы бар
